all: 
	g++ blockingMMM.cpp -o blockingMMM
	g++ matrixMatrixMult.cpp -o matrixMatrixMult
	g++ parallelMatrixMatrixMult.cpp -o parallelMatrixMatrixMult

clean:
	rm -fv blockingMMM matrixMatrixMult parallelMatrixMatrixMult